### ISSUE TITLE
Problem on WinogradConv Op when training from scratch

### ISSUE THREAD

**Issue by stoneyang** [xingyul/Sparse-Winograd-CNN#2]
Hi, @xingyul :

Thanks for sharing your research, and its implementation. 

When training ResNet-18 from scratch, I encountered the following problem to the `WinogradConv` operator: 

`'TypeError: 'NoneType' object has no attribute '__getitem__'`

The problem pointer implies the bug occurred on [this line](https://github.com/xingyul/Sparse-Winograd-CNN/blob/8e6c7197753938f342a96a4bf46ce5e36d5348db/ResNet-18-var/imagenet-resnet-transWino-prune.py#L119). 

Any suggestions would be appreciated! 
Thanks in advance. 

Cheers!

P.S.:

Ubuntu 16.06
gcc: 5.4.0
cuda: 8.0.61
tensorflow: 1.4
tensorpack: commit [0086e156c](https://github.com/ppwwyyxx/tensorpack/commit/0086e156c7a8c769fffea2214242c1b5767359d7)

**Comment by xingyul** [comment]
This is a bug. "use_mask" should be used instead of "test". Thanks for catching this!

**Comment by stoneyang** [comment]
Thanks for fixing the issue!
