### ISSUE TITLE
ValueError("as_list() is not defined on an unknown TensorShape.") due to WinogradImTrans and  WinogradConv op

### ISSUE THREAD

**Issue by Swas99** [xingyul/Sparse-Winograd-CNN#7]
Hi @xingyul 

Thanks for sharing your research, and its implementation.

When training ResNet-18 from scratch (also with fake data), I encountered the following problem due to the WinogradImTrans/WinogradConv operator:
ValueError("as_list() is not defined on an unknown TensorShape.")

> Traceback (most recent call last):
>   File "imagenet-resnet-transWino-prune.py", line 404, in <module>
>     launch_train_with_config(config, trainer)
>   File "/usr/lib/python3.7/site-packages/tensorpack/train/interface.py", line 91, in launch_train_with_config
>     model.build_graph, model.get_optimizer)
>   File "/usr/lib/python3.7/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/tensorpack/train/tower.py", line 224, in setup_graph
>     train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
>   File "/usr/lib/python3.7/site-packages/tensorpack/train/trainers.py", line 101, in _setup_graph
>     grad_list = self._builder.call_for_each_tower(tower_fn)
>   File "/usr/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 159, in call_for_each_tower
>     return DataParallelBuilder.build_on_towers(self.towers, tower_fn, devices)
>   File "/usr/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 122, in build_on_towers
>     return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 117, in call_for_each_tower
>     ret.append(func())
>   File "/usr/lib/python3.7/site-packages/tensorpack/train/tower.py", line 280, in get_grad_fn
>     return compute_grad_from_inputs(*inputs)
>   File "/usr/lib/python3.7/site-packages/tensorpack/train/tower.py", line 255, in compute_grad_from_inputs
>     cost = get_cost_fn(*inputs)
>   File "/usr/lib/python3.7/site-packages/tensorpack/tfutils/tower.py", line 290, in __call__
>     output = self._tower_fn(*args)
>   File "imagenet-resnet-transWino-prune.py", line 131, in build_graph
>     l_bra = BatchNorm('res2a_bn2b', l_bra)
>   File "/usr/lib/python3.7/site-packages/tensorpack/models/registry.py", line 138, in wrapped_func
>     outputs = func(*args, **actual_args)
>   File "/usr/lib/python3.7/site-packages/tensorpack/models/tflayer.py", line 66, in decorated_func
>     return func(inputs, **ret)
>   File "/usr/lib/python3.7/site-packages/tensorpack/models/batch_norm.py", line 174, in BatchNorm
>     shape = inputs.get_shape().as_list()
>   File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1079, in as_list
>     raise ValueError("as_list() is not defined on an unknown TensorShape.")
> 

The problem seems to happen after the first Winograd transformation and convolution operation [here](https://github.com/xingyul/Sparse-Winograd-CNN/blob/8e6c7197753938f342a96a4bf46ce5e36d5348db/ResNet-18-var/imagenet-resnet-transWino-prune.py#L118-L119)

After some debugging, I found that the data before these operations was as follows:
Before the first BatchNorm:
> l = Tensor("tower0/pool1/output:0", shape=(?, 56, 56, 64), dtype=float32, device=/device:GPU:0)

After the first BatchNorm:
> l_bra = Tensor("tower0/res2a_bn2a/output:0", shape=(?, 56, 56, 64), dtype=float32, device=/device:GPU:0)

After WinogradImTrans op:
> l_bra = Tensor("tower0/WinogradImTrans_2a_2a/Relu:0", dtype=float32, device=/device:GPU:0)

After WinogradConv op:
> l_bra Tensor("tower0/Winograd_W2a_2a/Winograd2x2Conv:0", dtype=float32, device=/device:GPU:0)

The issue is perhaps because the shape attribute is missing after the WinogradImTrans and  WinogradConv operations. I am not sure how to fix this.

Can you please provide any suggestions!
Thanks in advance.

**Comment by xingyul** [comment]
This code was tested under python 2.7. I'm not sure its behavior under python 3. Could you try using python 2.7?
