### ISSUE TITLE
Question about the CNN kernel size.

### ISSUE THREAD

**Issue by zwxandy** [xingyul/Sparse-Winograd-CNN#8]
Hi, I am very interested in your work! I have a little question about the kernel size.

In your paper, you use 3x3 kernels for different CNN models on three datasets. In this code, I wonder whether "winograd2x2_conv" means 2x2 kernel or 2x2 output patch (which is equivalent to p=4 as shown in the red tile below)? 

<img width="612" alt="截屏2023-02-19 11 39 23" src="https://user-images.githubusercontent.com/88173103/219914986-bfceda03-c588-429b-b159-4fd44ad59b16.png">

Thank you very much!

**Comment by xingyul** [comment]
@zwxandy, sorry for the late response. "winograd2x2_conv" takes a 4x4 input patch as input and convolve with a 3x3 kernel to produce a 2x2 output patch.
